### ISSUE TITLE
Missing EPW file for WMO 725776

### ISSUE THREAD

**Issue by BenjaminStuermer** [IMMM-SFA/diyepw#15]
When attempting to process the three ISD files for WMP 725776, an exception is generated because there is no EPW file present for that WMO in Energy_Plus_TMY3_EPW/

I think that we can solve this either by getting the missing EPW and adding it, or by removing those ISD files.

**Comment by amandadsmith** [comment]
Addressed with https://github.com/IMMM-SFA/diyepw/pull/17
