### ISSUE TITLE
Capture errors printed to screen in create_amy_epw_files.py

### ISSUE THREAD

**Issue by amandadsmith** [IMMM-SFA/diyepw#21]
We've got great information being shown at console, e.g.

> 727676-24013-2019: The longest set of missing records for Sea_Level_Pressure is 49, but the max allowed is 48

but we're not capturing that in create_amy_epw_files_output. Can we find a way to deliver this information in the CSV file? For the above example, upon seeing this info I would probably prefer to go ahead and have it create the AMY file for 727676-24013-2019, but I might miss it scrolling through all the "Processing" and "Problem processing" messages.

**Comment by BenjaminStuermer** [comment]
@amandadsmith We had a bug in the code that was causing some errors to get overwritten by others. In the current state of the "package" branch, create_amy_files_output/errors.csv has this output in it.
