### ISSUE TITLE
Make downloading missing files optional

### ISSUE THREAD

**Issue by BenjaminStuermer** [IMMM-SFA/diyepw#28]
Currently, if a TMY3 or ISD Lite file is missing, it will automatically be downloaded from EnergyPlus or NOAA. The code needs to be updated so that the default behavior instead will be to require user interaction for this download to take place. If the user does not wish to download the file, instructions for downloading it manually will be given.

Concurrently, the file download method itself will be made public so that users can invoke it to download the files manually.

**Comment by BenjaminStuermer** [comment]
@crvernon This is not exactly what you asked for (the script to fail if a file is missing, and a config option to be required for the download to be automatically triggered) but I think it's a good comprimise that isn't as big a hit to user friendliness. I am imagining that the package functions will take boolean arguments controlling whether downloading is permitted for missing files, and if files are found to be missing, the scripts can prompt the user for (y/n) feedback indicating whether the automatic download should be permitted. Thus, the package won't automatically download files, but our script users can simply respond to a prompt instead of having to set up a config file.

@amandadsmith I'd like your thoughts on this too before I proceed with developing this change, to make sure that we're staying close enough to your vision for how this tool should work.

**Comment by BenjaminStuermer** [comment]
Note: this will be added to the (increasingly poorly named) csv_based_script branch, which represents the current completed state of all our functionality prior to my beginning development of NetCDF support.

**Comment by BenjaminStuermer** [comment]
The requirement that the file download methods be made public was included in the request to make this change, so I included it in the ticket description. However, file downloads are already in their own dedicated methods: ´get_noaa_isd_lite_file(wmo_index:int, year:int)´ and `get_tmy_epw_file(wmo_index:int)` each take the arguments indicated and return the path to the file, whether it has been found locally on the system or had to be downloaded.

**Comment by BenjaminStuermer** [comment]
The download methods `get_noaa_isd_lite_file()` and `get_tmy_epw_file()` have been refactored. They now raise an Exception by default if the requested file is missing from its destination directory. An argument `allow_downloads` must be passed as True in order to allow any file to be downloaded. If it is not passed, the resulting error message includes the instruction that the argument can be added to allow the file to be downloaded automatically.

**Comment by crvernon** [comment]
@BenjaminStuermer this sounds reasonable to me.  Thanks for addressing this concern.
