### ISSUE TITLE
Split scripts into separate repository

### ISSUE THREAD

**Issue by BenjaminStuermer** [IMMM-SFA/diyepw#31]
I have proposed splitting this project into two separate repositories:

- The DIYEPW Python package, which would contain everything in the current repository's lib/diyepw/ directory.
- The DIYEPW Script toolkit, which would contain everything else currently in the repository.

The expected convention for a repository containing a Python package is that the package itself makes up the entire contents of a repository. The scripts and associated input files are not part of the package - they were specifically requested to be written as command-line tools, which means a user interacts with them in a fundamentally different way than with package code.

If we split them, users who are interested in using the prepared command-line scripts can clone the appropriate repository, and users who are interested in embedding DIYEPW capabilities into their own Python scripts can install the package. If they remain in the same repository, then we have an odd situation where users who want the command-line scripts also have to download the entire package code, even though they should be installing it via a package manager rather than locally.

I'd like to make sure all three of us are on board with this solution (or some alternative) before I proceed, since it's a fairly substantial change to the project.

**Comment by amandadsmith** [comment]
I support this split. I think the fairly substantial changes have been made and we do actually have two possible audiences (of which I am the probably rare crossover).  

@crvernon may have concerns we haven't thought of, or can create the new repo if we're all in agreement.

**Comment by crvernon** [comment]
I agree with this as well. Let's proceed. Thanks!

**Comment by BenjaminStuermer** [comment]
The scripts have been relocated to https://github.com/IMMM-SFA/diyepw-scripts. In the process, I have removed the inputs that were previously included with the scripts, and have added instructions for downloading them from the NOAA website. I intend to add a script later that lets you specify a set of WMOs and years and download ISD Lite files into a directory of your choice for use in the original step-by-step workflow.

@amandadsmith Please take a look at the README in the new repository and let me know if you see anything that is missing.
