### ISSUE TITLE
JOSS review #2: Paper

### ISSUE THREAD

**Issue by amandadsmith** [IMMM-SFA/diyepw#56]
> ## Paper
> * [x]  L21: "Its output is _a_ weather file"
> * [x]  L25-26: The separation of `diyepw` and `diyepw-scripts` seems to be outdated: [Implement cli within main repo and remove the diyepw-scripts repo IMMM-SFA/diyepw#51](https://github.com/IMMM-SFA/diyepw/issues/51)
> * [x]  L51f: Could you add another sentence on the functionality/background of LAF (apart from the limitations)?
> * [x]  references: many links are duplicated, could you remove the duplicates?
> * [x]  references: could you round out the citations of `numpy`, `pandas`, `xarray`? I.e. with DOI following instructions at https://numpy.org/citing-numpy/, https://pandas.pydata.org/about/citing.html, http://xarray.pydata.org/en/stable/getting-started-guide/faq.html#how-should-i-cite-xarray

**Comment by amandadsmith** [comment]
@thurber The pandas team requests a citation corresponding the version of pandas used. I wanted to confirm our required version but I don't see pandas listed in [setup](https://github.com/IMMM-SFA/diyepw/blob/joss-paper/setup.py) or on the [docs](https://diyepw.readthedocs.io/en/latest/README.html). Is this an oversight on our part, or should I be looking somewhere else?

**Comment by thurber** [comment]
@amandadsmith, good point, we aren't being explicit about this dependency (and possibly others). Right now this only works since `xarray` depends on `pandas`. I'll add an explicit dependency on `pandas==1.3.2` as i work through the other issues.

**Comment by amandadsmith** [comment]
@thurber Perfect, thanks!
